### ISSUE TITLE
Support more OpenStack versions

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-cinder-plugin#16]
In https://github.com/openvstorage/framework-cinder-plugin/issues/15 we added support for Liberty, this ticket is for Kilo and up.

**Comment by khenderick** [comment]
@wimpers, I'm a bit confused. `Kilo and up` includes `Liberty` as `Kilo` is older than `Liberty`. Besides that, does it make much sense to first focus on two [EOL](https://releases.openstack.org/) releases? I don't think it makes sense to put effort in any release older than `Newton`.

**Comment by wimpers** [comment]
Righ... i mean Mikata and up.

**Comment by khenderick** [comment]
@wimpers, `Mikata` will be EOL before we will ever be able to release support for it.

**Comment by wimpers** [comment]
The customer wants Liberty and supports it themselves.

**Comment by khenderick** [comment]
Makes sense. In any case, our previous efforts got to the point where we could use the Cinder driver for creating/deleting/whatever actions in combination with edge on our own local setups. So I don't think there's much to do. If issues would arise, then the customer could raise specific tickets.

**Comment by hoanhdo** [comment]
i testing integrate with openstack newton.
I working cinder newton : create delete volume.
But integrate with libvirt error.

> libvirtError: unsupported configuration: unknown protocol type 'openvstorage'
and config disk 

> <disk type="network" device="disk">
      <driver name="qemu" type="raw"/>
      <source protocol="openvstorage" snapshot_timeout="120" name="ovs"/>
      <host name="172.16.86.132" port="26203" transport="tcp"/>
      <target bus="virtio" dev="vda"/>
    </disk>


I installed package libvirt0 in repo, then error:

> 2017-02-16 02:45:06.050 15035 ERROR oslo_messaging.rpc.server Stdout: u"Formatting 'openvstorage+tcp:172.16.86.132:26203/', fmt=raw size=1073741824\n"
2017-02-16 02:45:06.050 15035 ERROR oslo_messaging.rpc.server Stderr: u'qemu-img: openvstorage+tcp:172.16.86.132:26203/: server and volume name must be specified\n'

libvirt call cinder create but not pass server vpool and vdisk
Thanks

**Comment by wimpers** [comment]
@hoanhdo please check  https://github.com/openvstorage/framework-cinder-plugin/issues/17 That GH ticket is used for OpenStack Newton . 
I will close this one . If other Open Stack versions are required, let's open a new  GH issue.
