### ISSUE TITLE
Cinder / nova plugin feature set

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework-cinder-plugin#17]
# Feature set cinder-nova plugins

These features are being fixed on the following branch: https://github.com/openvstorage/framework-cinder-plugin/tree/ovs-23-cinder-cleanup

## Cinder

| Feature | Description | Works? | Priority |
| :------------- |:-------------:| :-----: | -----: |
| Create empty volume | Creates a empty volume in Open vStorage | YES | / |
| Create boot volume | Creates a volume with a image loaded into it | YES | / |
| Create backup volume from existing volume | Should trigger cloning in Open vStorage, REQUIRES NEW DRIVER AS SEEN IN https://github.com/openvstorage/framework-cinder-plugin/issues/17#issuecomment-289438236 | BLOCKED | 2 |
| Create volume from existing volume | Should trigger cloning in Open vStorage, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/0518dea8d13092c82b692e6e78611c9c053f5a9e | YES | 2 |
| Extending a existing volume | Resize a certain volume, only enlarging the volume is supported, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/4d2da3764232586698dda240889f459f3a9d1277 | YES | 3 |
| Create snapshot from volume | Should trigger volume snapshotting in Open vStorage, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/0a08407dabc334f59941b51e86256aa7c543cb08 | YES | 2 |
| Delete snapshot from volume | Should trigger delete volume snapshot in Open vStorage, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/0a08407dabc334f59941b51e86256aa7c543cb08 | YES | 2 |
| Create volume from snapshot | Should trigger clone from certain snapshot, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/3683f5cc4d15df15391730b4c1cfa1d3220c1bd6 | YES | 2 |
| Upload volume to image | Should trigger `qemu-img convert ...` to a file, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/a7adb9cb8b7ff1cd8bb0eb20da7b8ff9eaf98ab5 | YES | / |

## Nova

| Feature | Description | Works? | Priority |
| ------------- |:-------------:| :-----:| -----: |
| Create instance with boot volume | Should attach a VM to a boot volume | YES | / |
| Detach volume from instance | Should detach a volume from a instance | YES | / |
| Attach another disk to a instance | Should add a new Open vStorage disk in the XML, FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/8a490edef77576360ce8250ffe08553336383ea0 | YES | 1 |
| Attach a cloned disk to a instance | Should add a new Open vStorage disk in XML but `source_path` is missing. FIXED IN https://github.com/openvstorage/framework-cinder-plugin/commit/9e3bd0e9c0771e130e4866cde1842603c7ba6091 | YES | 1 |
| Test VM migration between compute nodes | Should work in theory as this works in OVH | UNTESTED | 2 |

**PRIORITY SCALE:** 1 is highest; 3 is lowest; / to be determined, will not be fixed or already works

**Comment by kinvaris** [comment]
due to new implementation, I broke some stuff:
* Create snapshot
* Delete snapshot

Fixed:
* Extend volume after I broke it

Now works: 
* Create volume from existing volume

https://github.com/openvstorage/framework-cinder-plugin/commit/0518dea8d13092c82b692e6e78611c9c053f5a9e

**Comment by kinvaris** [comment]
After debugging the issue I got yesterday with attaching a instance to a cloned volume with no `source_path`. I've seen the following:
```
2017-03-24 09:53:09.543 DEBUG nova.virt.libvirt.volume.openvstorage_edge [req-617a212c-134f-49a7-8739-9772f1adf868 admin admin] libovsvolumedriver.libvirt.get_config {u'driver_volume_type': u'openvstorage_edge', u'volume_backend_name': u'myvpool01', 'serial': u'3763c90b-f2e5-4a93-a556-f2a0af06963f', u'data': {u'encrypted': False, u'device_path': None, u'qos_specs': None, u'access_mode': u'rw'}, 'connector': {'platform': 'x86_64', 'host': 'dsa-aio-ctrl', 'do_local_attach': False, 'ip': '10.100.198.201', 'os_type': 'linux2', 'multipath': False, 'initiator': 'iqn.1993-08.org.debian:01:2dabbbc0d6f'}} {'bus': u'virtio', 'boot_index': '1', 'type': u'disk', 'dev': u'vda'} from (pid=30114) get_config /opt/stack/nova/nova/virt/libvirt/volume/openvstorage_edge.py:46
```

For this feature to work the `volume_backend_name` in `/etc/cinder/cinder.conf` will have to be the same as the vPool name in Open vStorage.

**Comment by kinvaris** [comment]
A new implementation for volume deployment. As seen in de `/etc/cinder/cinder.conf`
```
[myvpool01]
volume_backend_name = myvpool01
volume_driver = cinder.volume.drivers.openvstorage_edge.OpenvStorageEdgeVolumeDriver
management_ips = 10.100.199.192
vpool_guid = 7968a798-a0ab-4f6a-8f3d-32f785215307
username = admin
password = admin
port = 443
```

This gives you the ability to load balance the volume deployment across the the storagedrivers of the vpool via the `vpool_guid`

**Comment by kinvaris** [comment]
I've noticed the following during feature implementation: `Create backup volume from existing volume`

This feature requires a whole new driver for `cinder`. As seen in `/etc/cinder/cinder.conf`:
```
## Cinder Backup
backup_driver = cinder.backup.drivers.swift
backup_metadata_version = 2
backup_compression_algorithm = zlib
swift_catalog_info = object-store:swift:internalURL
backup_swift_auth = per_user
backup_swift_container = volumebackups
backup_swift_object_size = 52428800
backup_swift_retry_attempts = 3
backup_swift_retry_backoff = 2
```

In this location: `/openstack/venvs/cinder-14.1.1/lib/python2.7/site-packages/cinder/backup/drivers/` we would have to create a new `cinder-backup` driver.

The code is already prepped for this module in commit: https://github.com/openvstorage/framework-cinder-plugin/commit/f906b0bfa6f62ed6060bc30f1274f4cc5e493a4b

A good example to base the `cinder-backup` driver on is the one of swift: `/openstack/venvs/cinder-14.1.1/lib/python2.7/site-packages/cinder/backup/drivers/swift.py`

**Comment by kinvaris** [comment]
Nothing is managed by the internal libovsvolumedriver anymore. Except `copy_image_to_volume` & `copy_volume_to_image` are using the command line `qemu-img`.
The rest is using the API

Fixed in https://github.com/openvstorage/framework-cinder-plugin/commit/a7adb9cb8b7ff1cd8bb0eb20da7b8ff9eaf98ab5

**Comment by saelbrec** [comment]
On top of the above mentioned features of cinder backup and nova migration which are not implemented/tested, to following items need to be taken into account when continuing the work on this.
- [ ] Package the OVS FWK rest client
- [ ] Think about possible integration of OVS template capability
- [ ] Upload volume to image: investigate why the removal of the image from the local path immediately after upload to glance seems to be nothing more than a reference in glance. Is the upload async or done with wrong params?
- [ ] Support for change volume type? Purely OVS wise this would mean the volume has to end up on another vpool, when different vpools would use the same backend the best integration would be a volume detach/attach to namespace operation. In all other cases we require a full data copy.
- [ ] Nova snapshot fails with a not implemented error. Needs to be investigated further(libvirt or qemu) and see what we can do.

**Comment by wimpers** [comment]
closing this issues and created https://github.com/openvstorage/framework-cinder-plugin/issues/18 as follow up for the loose ends.
