### ISSUE TITLE
Cinder / nova plugin loose ends

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-cinder-plugin#18]
Follow up on https://github.com/openvstorage/framework-cinder-plugin/issues/17 where features of cinder backup and nova migration are not implemented/tested, so following items need to be taken into account when continuing the work on this.
- [ ] Package the OVS FWK rest client
- [ ] Think about possible integration of OVS template capability
- [ ] Upload volume to image: investigate why the removal of the image from the local path immediately after upload to glance seems to be nothing more than a reference in glance. Is the upload async or done with wrong params?
- [ ] Support for change volume type? Purely OVS wise this would mean the volume has to end up on another vpool, when different vpools would use the same backend the best integration would be a volume detach/attach to namespace operation. In all other cases we require a full data copy.
- [ ] Nova snapshot fails with a not implemented error. Needs to be investigated further(libvirt or qemu) and see what we can do.

**Comment by hoannv46** [comment]
Hi @wimpers.

Cinder has a important feature, it create a volume then attach volume to existing instances.
Now ,attach_volume method in driver  do nothing.

Thanks.

Hoan.

**Comment by wimpers** [comment]
Hi @hoanhdo, I believe you are referring to https://github.com/openvstorage/framework-cinder-plugin/issues/19 . Thanks for reporting that one. The cinder plugin is fully functional with the Newton release.  We currently don't have the bandwidth to validate the  Octa release.

**Comment by hoannv46** [comment]
@wimpers 
I am not referring #19 .
Because #19, i installed newton realease .This feature in newton realease.
Thanks.

**Comment by hoannv46** [comment]
One more interesting feature, both glance and cinder use OpenVStorage, it can zero copy, time to create volume from image is very fast.

Thanks.

**Comment by wimpers** [comment]
This plugin is no longer used and can be replaced by a plugin that uses iSCSI.
