### ISSUE TITLE
Support Ocata OpenStack versions

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/framework-cinder-plugin#19]
Hi all.

Currently, i install ocata openstack.
I follow config guide new openstack. 
Create, delete cinder-volume successfully, but cannot create instances.
Because libvirtd service.

> Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-alpha: internal error: unable to execute QEMU command 'query-cpu-definitions': The co
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-cris: internal error: unable to execute QEMU command 'query-cpu-definitions': The com
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-lm32: internal error: unable to execute QEMU command 'query-cpu-definitions': The com
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-m68k: internal error: unable to execute QEMU command 'query-cpu-definitions': The com
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-microblaze: internal error: unable to execute QEMU command 'query-cpu-definitions': T
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-microblazeel: internal error: unable to execute QEMU command 'query-cpu-definitions':
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-mips: internal error: unable to execute QEMU command 'query-cpu-definitions': The com
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-mipsel: internal error: unable to execute QEMU command 'query-cpu-definitions': The c
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:13 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-mips64: internal error: unable to execute QEMU command 'query-cpu-definitions': The c
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-mips64el: internal error: unable to execute QEMU command 'query-cpu-definitions': The
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-or32: internal error: unable to execute QEMU command 'query-cpu-definitions': The com
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-sh4: internal error: unable to execute QEMU command 'query-cpu-definitions': The comm
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-sh4eb: internal error: unable to execute QEMU command 'query-cpu-definitions': The co
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-sparc: internal error: unable to execute QEMU command 'query-cpu-definitions': The co
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-sparc64: internal error: unable to execute QEMU command 'query-cpu-definitions': The 
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-unicore32: internal error: unable to execute QEMU command 'query-cpu-definitions': Th
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-xtensa: internal error: unable to execute QEMU command 'query-cpu-definitions': The c
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: internal error: unable to execute QEMU command 'query-cpu-definitions': The command query-cpu-definitions has not been found
Jul 05 15:01:14 hoannv-ovstorage-openstack-ansible libvirtd[6000]: Failed to probe capabilities for /usr/bin/qemu-system-xtensaeb: internal error: unable to execute QEMU command 'query-cpu-definitions': The
Jul 05 15:01:46 hoannv-ovstorage-openstack-ansible systemd[1]: Stopping Virtualization daemon...
Jul 05 15:01:46 hoannv-ovstorage-openstack-ansible systemd[1]: Stopped Virtualization daemon.

and log nova-compute.log

> 2017-07-05 15:28:49.921 6108 INFO nova.virt.driver [req-19856000-c8c9-42df-9b11-d62c6018d4ce - - - - -] Loading compute driver 'libvirt.LibvirtDriver'
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver [req-19856000-c8c9-42df-9b11-d62c6018d4ce - - - - -] Unable to load the virtualization driver
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver Traceback (most recent call last):
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver   File "/openstack/venvs/nova-15.1.5/lib/python2.7/site-packages/nova/virt/driver.py", line 1617, in load_compute_driver
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver     virtapi)
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver   File "/openstack/venvs/nova-15.1.5/lib/python2.7/site-packages/oslo_utils/importutils.py", line 44, in import_object
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver     return import_class(import_str)(*args, **kwargs)
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver   File "/openstack/venvs/nova-15.1.5/lib/python2.7/site-packages/nova/virt/libvirt/driver.py", line 348, in __init__
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver     libvirt = importutils.import_module('libvirt')
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver   File "/openstack/venvs/nova-15.1.5/lib/python2.7/site-packages/oslo_utils/importutils.py", line 73, in import_module
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver     __import__(import_str)
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver   File "/openstack/venvs/nova-15.1.5/lib/python2.7/site-packages/libvirt.py", line 28, in <module>
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver     raise lib_e
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver ImportError: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.2.0' not found (required by /openstack/venvs/nova-15.1.5/lib/python2.7/site-packages/libvirtmod.so)
2017-07-05 15:28:50.348 6108 ERROR nova.virt.driver 

I think qemu in ocata openstack has diffirent command.

Thanks all.

Hoan.

**Comment by wimpers** [comment]
Closing this one down as integration with OpenStack should happen through iSCSI and not through a custom plugin.
